#!/usr/bin/env python3
"""
Music-specific linter for knowledge-base vault files.

Checks:
  - SVG files produced by kb_svg.py: has kb-meta comment, correct xmlns, non-empty body
  - MIDI files: valid MThd header, Format 0 or 1, at least 1 track
  - Document .md files in music topics: required front-matter fields,
    no empty H2 sections, valid wiki-link format
  - Diagram .json files in music topics: has 'title', 'nodes', 'layers' keys;
    nodes reference valid layer IDs; connections reference valid node IDs

Usage:
  kb_validate_music.py <path> [<path> ...]
  kb_validate_music.py "music/**/*.svg"   (glob expansion)
  kb_validate_music.py --json-report      (output structured JSON instead of text)

Exit codes:
  0 — all files passed
  1 — one or more files have lint errors
"""

import argparse
import glob
import json
import re
import struct
import sys
from pathlib import Path


# ── Result types ──────────────────────────────────────────────────────────────

class LintResult:
    def __init__(self, path: str):
        self.path = path
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, msg: str) -> None:
        self.errors.append(msg)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)

    @property
    def ok(self) -> bool:
        return len(self.errors) == 0


# ── SVG lint ──────────────────────────────────────────────────────────────────

def lint_svg(path: Path) -> LintResult:
    r = LintResult(str(path))
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as e:
        r.error(f"cannot read: {e}")
        return r

    if 'xmlns="http://www.w3.org/2000/svg"' not in content:
        r.error("missing SVG xmlns declaration")
    if "<!-- kb-meta:" not in content:
        r.warn("missing kb-meta comment (not generated by kb_svg.py)")
    if "<svg" not in content:
        r.error("no <svg> root element found")
    if "</svg>" not in content:
        r.error("unclosed <svg> element")
    body_content = re.sub(r'<\?xml[^>]*\?>', '', content)
    body_content = re.sub(r'<!--.*?-->', '', body_content, flags=re.DOTALL)
    body_content = re.sub(r'<svg[^>]*>', '', body_content)
    body_content = body_content.replace('</svg>', '').strip()
    if len(body_content) < 10:
        r.error("SVG body appears empty (no drawable elements)")
    return r


# ── MIDI lint ─────────────────────────────────────────────────────────────────

def lint_midi(path: Path) -> LintResult:
    r = LintResult(str(path))
    try:
        data = path.read_bytes()
    except OSError as e:
        r.error(f"cannot read: {e}")
        return r

    if len(data) < 14:
        r.error("file too small to be a valid MIDI file")
        return r
    if data[:4] != b"MThd":
        r.error(f"invalid MIDI header: expected MThd, got {data[:4]!r}")
        return r
    header_len = struct.unpack(">I", data[4:8])[0]
    if header_len != 6:
        r.error(f"unexpected MThd length {header_len} (expected 6)")
    fmt = struct.unpack(">H", data[8:10])[0]
    if fmt not in (0, 1):
        r.warn(f"MIDI format {fmt} (expected 0 or 1)")
    n_tracks = struct.unpack(">H", data[10:12])[0]
    if n_tracks == 0:
        r.error("MIDI file has 0 tracks")
    # Check that declared track count matches MTrk chunks
    actual_tracks = len(re.findall(b"MTrk", data))
    if actual_tracks != n_tracks:
        r.error(f"header declares {n_tracks} tracks but {actual_tracks} MTrk chunks found")
    return r


# ── Markdown document lint ────────────────────────────────────────────────────

_WIKILINK_RE = re.compile(r'\[\[([^\]]+)\]\]')
_BROKEN_WIKILINK_RE = re.compile(r'\[\[([^\]]*\s[^\]]*\.(?:json|md))\]\]')

def lint_markdown(path: Path) -> LintResult:
    r = LintResult(str(path))
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as e:
        r.error(f"cannot read: {e}")
        return r

    lines = content.splitlines()

    # H1 required
    h1_lines = [l for l in lines if l.startswith("# ") and not l.startswith("## ")]
    if not h1_lines:
        r.error("missing H1 title (# Title)")

    # No empty H2 sections (H2 followed immediately by another H2 or EOF)
    for i, line in enumerate(lines):
        if line.startswith("## "):
            next_h = next(
                (j for j in range(i + 1, len(lines)) if lines[j].startswith("## ")),
                None,
            )
            section_lines = lines[i + 1:next_h] if next_h else lines[i + 1:]
            body = [l for l in section_lines if l.strip()]
            if not body:
                r.error(f"empty H2 section: {line.strip()!r}")

    # Wiki-links: spaces inside [[...]] containing filenames are suspicious
    for m in _BROKEN_WIKILINK_RE.finditer(content):
        r.warn(f"wiki-link with spaces in filename: [[{m.group(1)}]]")

    # Warn if no wiki-links at all in a music document
    if not _WIKILINK_RE.search(content) and len(lines) > 20:
        r.warn("no wiki-links found — consider cross-referencing related topics")

    return r


# ── Diagram JSON lint ──────────────────────────────────────────────────────────

def lint_diagram_json(path: Path) -> LintResult:
    r = LintResult(str(path))
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError as e:
        r.error(f"cannot read: {e}")
        return r
    except json.JSONDecodeError as e:
        r.error(f"invalid JSON: {e}")
        return r

    for key in ("title", "nodes", "layers"):
        if key not in data:
            r.error(f"missing required key: {key!r}")

    if "layers" in data and "nodes" in data:
        layer_ids = {l.get("id") for l in data["layers"] if isinstance(l, dict)}
        for node in data["nodes"]:
            if not isinstance(node, dict):
                continue
            nid = node.get("id", "?")
            layer = node.get("layer")
            if layer and layer not in layer_ids:
                r.error(f"node {nid!r} references unknown layer {layer!r}")

    if "connections" in data and "nodes" in data:
        node_ids = {n.get("id") for n in data["nodes"] if isinstance(n, dict)}
        for conn in data["connections"]:
            if not isinstance(conn, dict):
                continue
            cid = conn.get("id", "?")
            for endpoint in ("from", "to"):
                ref = conn.get(endpoint)
                if ref and ref not in node_ids:
                    r.error(f"connection {cid!r} {endpoint}={ref!r} references unknown node")

    return r


# ── Dispatcher ────────────────────────────────────────────────────────────────

def lint_file(path: Path) -> LintResult:
    suffix = path.suffix.lower()
    if suffix == ".svg":
        return lint_svg(path)
    if suffix in (".mid", ".midi"):
        return lint_midi(path)
    if suffix == ".md":
        return lint_markdown(path)
    if suffix == ".json":
        return lint_diagram_json(path)
    r = LintResult(str(path))
    r.warn(f"unrecognised file type {suffix!r}; skipped")
    return r


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="Music knowledge-base linter")
    ap.add_argument("paths", nargs="+", help="Files or globs to lint")
    ap.add_argument("--json-report", action="store_true",
                    help="Output structured JSON instead of text")
    args = ap.parse_args()

    expanded: list[Path] = []
    for pat in args.paths:
        matches = glob.glob(pat, recursive=True)
        if matches:
            expanded.extend(Path(m) for m in matches)
        else:
            expanded.append(Path(pat))

    results: list[LintResult] = []
    for p in expanded:
        if not p.exists():
            r = LintResult(str(p))
            r.error("file not found")
            results.append(r)
        else:
            results.append(lint_file(p))

    if args.json_report:
        out = []
        for r in results:
            out.append({"path": r.path, "errors": r.errors, "warnings": r.warnings, "ok": r.ok})
        print(json.dumps(out, indent=2))
    else:
        any_errors = False
        for r in results:
            for msg in r.errors:
                print(f"ERROR  {r.path}: {msg}", file=sys.stderr)
                any_errors = True
            for msg in r.warnings:
                print(f"WARN   {r.path}: {msg}")
            if r.ok and not r.warnings:
                print(f"OK     {r.path}")
        if not any_errors:
            print(f"\n✓ {len(results)} file(s) passed")

    sys.exit(0 if all(r.ok for r in results) else 1)


if __name__ == "__main__":
    main()
