import { test, expect, type Page } from '@playwright/test'
import { installMockFS } from './fixtures/fsMock'

// KB-002: per-document autosave drafts.
//
// Scope semantics: each vault gets a UUID-derived scope ID generated by
// `acquirePickerHandle` (`crypto.randomUUID().slice(0, 8)`); all draft
// localStorage keys are namespaced with that scope so two different
// vaults can't collide. We stub `crypto.randomUUID` to a deterministic
// value so the spec can read/write the scoped key itself without round-
// tripping through the running app to discover the scope.

const FIXED_SCOPE = 'testscop'
// `scopedKey('knowledge-base-draft:')` becomes `knowledge-base-draft:[scope]`,
// then the file path is appended — so the key is prefix-scope-path, not
// prefix-path-scope.
const DRAFT_KEY_FOR_A = `knowledge-base-draft:[${FIXED_SCOPE}]a.md`

async function setupFs(page: Page, seed: Record<string, string>) {
  await page.addInitScript(installMockFS)
  await page.addInitScript(() => {
    try { indexedDB.deleteDatabase('knowledge-base') } catch { /* ignore */ }
    try { localStorage.clear() } catch { /* ignore */ }
  })
  await page.addInitScript(() => {
    // First 8 chars of the picker's `crypto.randomUUID()` become the
    // directory scope ID; stable scope = stable localStorage key. The
    // Web Crypto object is frozen in some hosts, so install the override
    // on a wrapper rather than mutating the real prototype.
    const proxied = new Proxy(crypto, {
      get(target, prop, receiver) {
        if (prop === 'randomUUID') {
          return () => 'testscop-0000-0000-0000-000000000000'
        }
        const v = Reflect.get(target, prop, receiver)
        return typeof v === 'function' ? v.bind(target) : v
      },
    })
    Object.defineProperty(globalThis, 'crypto', {
      configurable: true,
      writable: true,
      value: proxied,
    })
  })
  await page.addInitScript((files) => {
    for (const filename of Object.keys(files)) {
      localStorage.setItem(`document-read-only:${filename}`, 'false')
    }
  }, seed)
  await page.goto('/')
  await page.locator('[data-testid="knowledge-base"]').waitFor()
  await page.evaluate((files) => {
    const m = (window as unknown as {
      __kbMockFS: { seed: (f: Record<string, string>) => void }
    }).__kbMockFS
    m.seed(files)
  }, seed)
}

async function openFolder(page: Page) {
  await page.getByRole('button', { name: 'Open Folder' }).click()
}

async function openFile(page: Page, name: string) {
  await page.getByTestId('explorer-tree').getByText(name).first().click()
  await expect(page.locator('.ProseMirror').first()).toBeVisible({ timeout: 5000 })
}

test.describe('KB-002: document autosave drafts', () => {
  test('typing into a document persists a draft to localStorage after the 500ms debounce', async ({ page }) => {
    await setupFs(page, { 'a.md': '# original' })
    await openFolder(page)
    await openFile(page, 'a.md')

    const editor = page.locator('.ProseMirror').first()
    await editor.click()
    await page.keyboard.press('End')
    await page.keyboard.type(' edited')

    // Debounce is 500ms; allow a small buffer for async writes.
    await page.waitForTimeout(900)

    const draft = await page.evaluate((key) => {
      const raw = localStorage.getItem(key)
      return raw ? (JSON.parse(raw) as { kind?: string; content?: string; savedAt?: number }) : null
    }, DRAFT_KEY_FOR_A)

    expect(draft).not.toBeNull()
    expect(draft!.kind).toBe('document')
    expect(draft!.content).toContain('edited')
    expect(typeof draft!.savedAt).toBe('number')
  })

  test('restore banner appears when a stored draft differs from disk; clicking Discard reverts to disk and the banner does not return', async ({ page }) => {
    await setupFs(page, {
      'a.md': '# disk version',
      'b.md': '# b',
    })
    await openFolder(page)
    // Open + save once so dirty=false on the source pane — that prevents
    // auto-save-on-switch from clobbering our injected draft when we hop
    // away and back below.
    await openFile(page, 'a.md')

    // Inject a draft at the scoped key directly. Using page.evaluate keeps
    // the test independent of the editor's keystroke timing.
    await page.evaluate(({ key, payload }) => {
      localStorage.setItem(key, JSON.stringify(payload))
    }, {
      key: DRAFT_KEY_FOR_A,
      payload: { kind: 'document', content: '# unsaved restored content', savedAt: Date.now() - 30_000 },
    })

    // Force a remount of the load effect by switching files and back.
    await openFile(page, 'b.md')
    await openFile(page, 'a.md')

    // Banner is visible.
    const banner = page.getByTestId('draft-restore-banner')
    await expect(banner).toBeVisible({ timeout: 5000 })
    await expect(banner).toContainText(/Restored unsaved changes/i)

    // Editor shows the restored draft, not disk content.
    await expect(page.locator('.ProseMirror').first()).toContainText('unsaved restored content')

    // Discard reverts to disk and dismisses the banner.
    await banner.getByRole('button', { name: 'Discard' }).click()
    await expect(banner).toBeHidden()
    await expect(page.locator('.ProseMirror').first()).toContainText('disk version')

    // Draft was removed from localStorage.
    const afterDiscard = await page.evaluate((key) => localStorage.getItem(key), DRAFT_KEY_FOR_A)
    expect(afterDiscard).toBeNull()

    // Hopping away and back must not raise the banner again — the draft is
    // gone for good.
    await openFile(page, 'b.md')
    await openFile(page, 'a.md')
    await page.waitForTimeout(300)
    await expect(page.getByTestId('draft-restore-banner')).toHaveCount(0)
  })

  test('beforeunload fires when any document is dirty', async ({ page }) => {
    await setupFs(page, { 'a.md': '# original' })
    await openFolder(page)
    await openFile(page, 'a.md')

    // Clean state — no guard installed yet.
    const beforeDirty = await page.evaluate(() => {
      const e = new Event('beforeunload', { cancelable: true })
      window.dispatchEvent(e)
      return e.defaultPrevented
    })
    expect(beforeDirty).toBe(false)

    // Type to flip the doc dirty.
    await page.locator('.ProseMirror').first().click()
    await page.keyboard.press('End')
    await page.keyboard.type(' edited')

    // Wait for the global dirty count to reflect the edit; the
    // shell-level useEffect that attaches the beforeunload listener
    // depends on `headerDirtyFiles.size` flipping above 0.
    await expect(page.getByTestId('dirty-stack-indicator')).toContainText(/unsaved/, { timeout: 3000 })

    const afterDirty = await page.evaluate(() => {
      const e = new Event('beforeunload', { cancelable: true })
      window.dispatchEvent(e)
      return e.defaultPrevented
    })
    expect(afterDirty).toBe(true)
  })

  test('save (Cmd+S) clears the draft', async ({ page }) => {
    await setupFs(page, { 'a.md': '# original' })
    await openFolder(page)
    await openFile(page, 'a.md')

    const editor = page.locator('.ProseMirror').first()
    await editor.click()
    await page.keyboard.press('End')
    await page.keyboard.type(' edited')

    // Wait for debounce to land the draft.
    await page.waitForTimeout(900)
    const beforeSave = await page.evaluate((key) => localStorage.getItem(key), DRAFT_KEY_FOR_A)
    expect(beforeSave).not.toBeNull()

    // Save via Cmd+S (or Ctrl+S on linux runners; chromium accepts both).
    await page.keyboard.press('Meta+s')

    // Draft must be cleared once the write to disk succeeds.
    await expect.poll(
      () => page.evaluate((key) => localStorage.getItem(key), DRAFT_KEY_FOR_A),
      { timeout: 3000 },
    ).toBeNull()
  })
})
